### ISSUE TITLE
fiftyone.core.media.MediaTypeError: Unsupported media type 'None'

### ISSUE THREAD

**Issue by bhack** [voxel51/zcore#2]
With  `python zeroshot_coreset_selection.py --dataset eurosat10 --data_dir ./data --results_dir ./results --embedding clip resnet18 --num_workers 10`
 ```python
File "/zcore/core/coreset/model_embed.py", line 49, in generate_embedding
    model_embed = dataset.compute_embeddings(model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/fiftyone/core/collections.py", line 3370, in compute_embeddings
    return fomo.compute_embeddings(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/fiftyone/core/models.py", line 855, in compute_embeddings
    raise fom.MediaTypeError(
fiftyone.core.media.MediaTypeError: Unsupported media type 'None'
```

**Comment by vijay-jaisankar** [comment]
Hello @bhack! I'm facing the same error as well; if you were able to solve the same, can you please share the fix? Thanks!

```py
Traceback (most recent call last):
  File "/kaggle/working/zcore/zeroshot_coreset_selection.py", line 42, in <module>
    main(args)
  File "/kaggle/working/zcore/zeroshot_coreset_selection.py", line 12, in main
    embeddings = cs.get_model_embedding(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kaggle/working/zcore/core/coreset/model_embed.py", line 66, in get_model_embedding
    model_embed = generate_embedding(args, model_name, embed_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kaggle/working/zcore/core/coreset/model_embed.py", line 49, in generate_embedding
    model_embed = dataset.compute_embeddings(model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fiftyone/core/collections.py", line 3446, in compute_embeddings
    return fomo.compute_embeddings(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fiftyone/core/models.py", line 855, in compute_embeddings
    raise fom.MediaTypeError(
fiftyone.core.media.MediaTypeError: Unsupported media type 'None'
```
